import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { PROJECT_ROOT } from "../config/load.ts";
import type { Db } from "../util/db.ts";
import { isPretend, type Config } from "../config/schema.ts";
import { outcomeSummary } from "./outcomes.ts";
import type { TuningRun } from "./tuner.ts";
import { log } from "../util/log.ts";

/**
 * Human-readable, rolling audit trail for the tuner (`src/learning/tuner.ts`).
 *
 * `tuning_runs` (SQL, `node src/cli.ts tuning`) is the real, unbounded audit
 * trail -- this file is a readable convenience view of the same runs, so a
 * human can watch the trend (including the boring "not enough evidence yet"
 * cycles) without a DB client. It is generated and gitignored, same as
 * `data/tuning.json` -- if the two ever disagree, the SQL table wins.
 *
 * Writes nothing at all while `learning.enabled` is false (see the early
 * return in `runTuning`) -- the file does not exist until a human turns
 * learning on.
 */

export const DEFAULT_LOG_PATH = "docs/self-improvement.md";

/** Oldest entries are trimmed past this count; the header always survives. */
const MAX_ENTRIES = 500;

const HEADER = `# Self-improvement log

Generated by \`src/learning/tuner.ts\` via \`appendSelfImprovementEntry()\`.
Do not hand-edit -- this file is regenerated/trimmed on every tuning run and
is gitignored. The real, unbounded audit trail is the \`tuning_runs\` SQL
table (\`node src/cli.ts tuning\`); this is a readable rolling window onto it.

## Objectives

1. **Increase the hit rate over time**, using the same hit/modest/dud verdict
   and component-separation evidence \`gatherEvidence()\` already computes --
   no metric here is invented beyond what \`src/learning/outcomes.ts\` measures.
2. **Never widen the money/safety boundary.** Every change is confined to
   \`src/learning/guardrails.ts\`'s existing \`TUNABLE\` allowlist; nothing
   under \`risk.*\`/\`devPosition.*\`/\`filters.*\`/\`launch.*\`/\`wallet.*\`/
   \`rpc.*\`/\`learning.*\` is ever reachable from this loop.
3. **Run often without pretending there's more evidence than there is.**
   \`learning.minSampleSize\` stays the authoritative floor -- a fast cadence
   just re-checks the same evidence sooner as more launches settle; it does
   not lower the bar for what counts as evidence.
4. **Leave a trail a human can actually read**, including the boring cycles,
   so a bad trend is visible before it needs \`node src/cli.ts tuning --clear\`
   instead of being noticed only after the fact.

---
`;

function resolveLogPath(path: string): string {
  return isAbsolute(path) ? path : resolve(PROJECT_ROOT, path);
}

function formatChange(c: { path: string; from: number; to: number; clamped: boolean }): string {
  return `  - \`${c.path}\`: ${c.from} \u2192 ${c.to}${c.clamped ? " (clamped)" : ""}`;
}

function formatRejection(r: { path: string; reason: string }): string {
  return `  - \`${r.path}\`: rejected -- ${r.reason}`;
}

function formatEntry(db: Db, cfg: Config, run: TuningRun): string {
  const when = new Date().toISOString();
  const mode = isPretend(cfg) ? "dry-run" : "live";
  const lines: string[] = [`## ${when} (${mode}, ${cfg.network})`];

  if (!run.ran) {
    lines.push(`Skipped: ${run.reason}`);
    return lines.join("\n");
  }

  const summary = outcomeSummary(db, cfg);
  lines.push(
    `Sample: ${run.sampleSize} settled launches ` +
    `(${summary.hits} hit / ${summary.modest} modest / ${summary.duds} dud). ` +
    `Applied: ${run.applied ? "yes" : "no"}.`,
  );
  if (run.rationale) lines.push("", run.rationale.trim());

  const accepted = run.result?.accepted ?? [];
  const rejected = run.result?.rejected ?? [];
  if (accepted.length) lines.push("", "Accepted:", ...accepted.map(formatChange));
  if (rejected.length) lines.push("", "Rejected:", ...rejected.map(formatRejection));
  if (!accepted.length && !rejected.length) lines.push("", "No changes proposed this run.");

  return lines.join("\n");
}

/** Split the body into individual `## ...` entries, newest-preserving order. */
function splitEntries(body: string): string[] {
  return body.split(/(?=^## )/m).filter((e) => e.trim().length > 0);
}

/** Trim to the header plus the most recent MAX_ENTRIES entries. */
function trim(content: string): string {
  const headerEnd = content.indexOf("---\n");
  if (headerEnd === -1) return content;
  const head = content.slice(0, headerEnd + 4);
  const entries = splitEntries(content.slice(headerEnd + 4));
  if (entries.length <= MAX_ENTRIES) return content;
  return head + entries.slice(-MAX_ENTRIES).join("");
}

/**
 * Append one entry for this tuning run -- called from every `runTuning()`
 * path except the disabled one, so the file records real runs AND the "not
 * enough evidence yet" cycles a fast cadence mostly produces early on.
 */
export function appendSelfImprovementEntry(
  db: Db, cfg: Config, run: TuningRun, path: string = DEFAULT_LOG_PATH,
): void {
  const file = resolveLogPath(path);
  mkdirSync(dirname(file), { recursive: true });

  const existing = existsSync(file) ? readFileSync(file, "utf8") : HEADER;
  const base = existing.endsWith("\n") ? existing : `${existing}\n`;
  const entry = `${formatEntry(db, cfg, run)}\n\n`;
  writeFileSync(file, trim(`${base}${entry}`), "utf8");

  log.debug("self-improvement log entry written", { file, ran: run.ran });
}
